### ISSUE TITLE
Docker run errors in get_predictions.py: /output/ files not found

### ISSUE THREAD

**Issue by anamnazir1** [Svdvoort/PrognosAIs_glioma#5]
Hi Svdvoort!

I am trying to reproduce your code on ubuntu 22 with rootless docker:   i am having this error can you guide me about it ? 

Resampling image and writing to disk ...
  Progress: 100%
  Writing image ...
  Resampling took 1.62s

transformix has finished at Thu May 16 16:02:44 2024.
Total time elapsed: 1.8s.

Traceback (most recent call last):
  File "/get_predictions.py", line 1, in <module>
    from PrognosAIs import Pipeline
  File "/usr/local/lib/python3.8/site-packages/PrognosAIs/Pipeline.py", line 8, in <module>
    import PrognosAIs.IO.utils as IO_utils
  File "/usr/local/lib/python3.8/site-packages/PrognosAIs/IO/utils.py", line 9, in <module>
    import numba.cuda
  File "/usr/local/lib/python3.8/site-packages/numba/__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
mv: cannot stat '/output/Predictions/Results': No such file or directory
rm: cannot remove '/output/PSNET*': No such file or directory
rm: cannot remove '/output/Predictions/Samples': No such file or directory
rm: cannot remove '/output/Predictions/config.yml': No such file or directory
rm: cannot remove '/output/Predictions/labels.txt': No such file or directory

**Comment by Svdvoort** [comment]
Hi,

This is most likely due to not having the correct folder structure or insufficient permissions for the output folder. Could you try the following things:

1. Ensure that your folder structure is the same as the one mentioned in [the readme](https://github.com/Svdvoort/PrognosAIs_glioma?tab=readme-ov-file#docker)
2. Post the full log that you get, not just the last part? 
3. Share any results that are in the output folder, if any are created? If they are not could you make sure that you have the appropriate permissions to create files in the output folder? 
4. Post the full command that you use to run the docker (Removing potential identifying information from the path)?

Rootless docker should work fine. I have run the Docker under Singularity as well, which did work. However, sometimes setting up rootless docker with the correct permissions for all folder can be a problem.

**Comment by anamnazir1** [comment]
I run it manually without docker with some modifications.  now the testing is running successfully.  Thank you!
Can you please tell me the training process you used for the specific images? I have following queries regarding your code

   1.  Does your code works for other dataset as well or it need to be trained?
   2.  If you have training file separate can you please mention it?
   3. Can we use another Model instead of UNet?

**Comment by Svdvoort** [comment]
I think all of these questions are answered in the paper that this code belongs to, so please check there for details: https://doi.org/10.1093/neuonc/noac166

For short answers:

1. Yes it should work without training, we validated the performance on an external dataset.
2. See the paper.
3. You can of course use whatever model you want, but then it would be sometime new, and not the work presented in the paper.
